### ISSUE TITLE
Usability Testing Recommendations : Home page changes

### ISSUE THREAD

**Issue by drogith** [biocaddie/BioCaddie-core-UI#2]
Update the home page to include more text about datamed, and less distractions.

Recommendations:
1) Remove text "Engaging The Community Toward a Data Discovery Index (DataMed v2.0)" and add clear definition of what datamed does. Example: "A Biomedical Data Discovery Index (DDI). You will find data from multiple repositories indexed for easy finding, accessing and citing biomedical data related to your search term. Search for any keyword to discover data related to the term"

2) Remove the two radio button ins the search.

3) Have a curated list of top 10 searches be appearing the input as suggestions

4) Remove Statistics, Top  Repositories, and New Features. Move them to "About" page

5) Remove "Pilot Projects", and move them to "About page".

6) Add a list of top 18 repositories, and top 12 data types as icons and text.

7) use tools tips to add information about repository / data type.

Recommended layout is attached. Also see http://data.gov for example.

![datamed_home_page](https://cloud.githubusercontent.com/assets/10734065/26085699/adf9fb52-39ab-11e7-8ad3-d5673d24a851.png)

**Comment by aegururaj** [comment]
This issue was moved to biocaddie/prototype_issues#296
