### ISSUE TITLE
Usability Testing Recommendations: Search Results Page

### ISSUE THREAD

**Issue by drogith** [biocaddie/BioCaddie-core-UI#3]
1) Provide information on how relevant searches are displayed (e.g. refer to data.gov)
2) Remove "Sort by" button - as there is only one way of sorting currently.
3) Adjust the display of the search results - see attached
    a) Make the checkboxes in one column
    b) Include Source, Data Download links
    c) Move the MetaData information to show the relevant terms highlighted. Discussion required to identify how to display Metadata box.

See attached for a prototype
![datamed_search_page](https://cloud.githubusercontent.com/assets/10734065/26087126/ac95d1ce-39b4-11e7-8c7c-a4dcb71817a5.png)

**Comment by aegururaj** [comment]
This issue was moved to biocaddie/prototype_issues#297
