### ISSUE TITLE
Usability Testing Recommendations : Dataset Page

### ISSUE THREAD

**Issue by drogith** [biocaddie/BioCaddie-core-UI#4]
1) Present key information on top of the page - example data.gov
    a) Title
    b) Date Last updated
    c) Description
    d) Access & Use Information
    e) Download links
    f) Dates
    g) All other metadata
![data_set_2](https://cloud.githubusercontent.com/assets/10734065/26087330/c10d4bae-39b5-11e7-8363-8bc1bce6a622.png)

2) Include Repository information in left menu. (See data.gov)
   a) Include Logo
   b) Repository Name
   c) Contact Information / webpage

3)  In future - include a right menu with statistics on related datasets visualization, people also searched for, etc. (See attached).
![data_set_1](https://cloud.githubusercontent.com/assets/10734065/26087331/c35b244e-39b5-11e7-9d87-64c46dc88309.png)

**Comment by aegururaj** [comment]
This issue was moved to biocaddie/prototype_issues#298
